import { FormEvent, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../api/client";

export function AISettings() {
  const client = useQueryClient(); const providers = useQuery({ queryKey: ["ai-providers"], queryFn: api.getProviders }); const models = useQuery({ queryKey: ["ai-models"], queryFn: api.getModels });
  const functions = useQuery({ queryKey: ["ai-functions"], queryFn: api.getAIFunctions }); const jobs = useQuery({ queryKey: ["ai-jobs"], queryFn: api.getAIJobs }); const notifications = useQuery({ queryKey: ["notifications"], queryFn: api.getNotifications }); const workflows = useQuery({ queryKey: ["workflows"], queryFn: api.getWorkflows }); const settings = useQuery({ queryKey: ["ai-settings"], queryFn: api.getAISettings });
  const [name, setName] = useState(""); const [type, setType] = useState("openai_compatible"); const [url, setUrl] = useState(""); const [key, setKey] = useState(""); const [model, setModel] = useState(""); const [inputPrice, setInputPrice] = useState("0"); const [outputPrice, setOutputPrice] = useState("0"); const [selectedProvider, setSelectedProvider] = useState(""); const [message, setMessage] = useState("");
  async function reload() { await Promise.all(["ai-providers", "ai-models", "ai-functions", "ai-jobs", "notifications", "workflows", "ai-settings"].map((queryKey) => client.invalidateQueries({ queryKey: [queryKey] }))); }
  async function saveProvider(event: FormEvent) { event.preventDefault(); try { const provider = await api.createProvider({ name, provider_type: type, base_url: url || undefined, api_key: key || undefined }); setName(""); setKey(""); setSelectedProvider(provider.id); setMessage("AI Provider 已保存；接下来添加模型。"); await reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Provider 保存失败"); } }
  async function saveModel(event: FormEvent) { event.preventDefault(); if (!selectedProvider) return setMessage("请先选择 Provider"); try { await api.createModel({ provider_id: selectedProvider, model_key: model, display_name: model, capabilities_json: ["summarize", "translate.en_to_zh", "extract.keywords", "classify"], cost_config_json: { input_per_million: Number(inputPrice) || 0, output_per_million: Number(outputPrice) || 0 } }); setModel(""); setMessage("模型已保存"); await reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "模型保存失败"); } }
  async function setOption(keyName: "auto_translate" | "auto_summary", value: boolean) { try { await api.saveAISettings({ [keyName]: value }); await reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "设置保存失败"); } }
  async function setBudget(value: string) { const amount = Number(value); if (!Number.isFinite(amount) || amount < 0) return; await api.saveAISettings({ monthly_ai_budget: amount }); await reload(); }
  return <section className="ai-settings"><h2>AI 控制台</h2><p className="settings-help">密钥只在保存时传给后端并加密，之后不会再次显示。</p><div className="ai-option"><label><input type="checkbox" checked={Boolean(settings.data?.auto_translate)} onChange={(event) => void setOption("auto_translate", event.target.checked)} /> 打开文章时自动翻译</label><label><input type="checkbox" checked={Boolean(settings.data?.auto_summary)} onChange={(event) => void setOption("auto_summary", event.target.checked)} /> 打开文章时自动总结</label><label>月度上限（USD）<input aria-label="月度 AI 预算" type="number" min="0" step="0.01" defaultValue={String(settings.data?.monthly_ai_budget ?? 0)} onBlur={(event) => void setBudget(event.target.value)} /></label></div>
    <details open><summary>AI Engines</summary><form onSubmit={saveProvider}><input aria-label="Provider 名称" placeholder="例如 OpenAI / Ollama" value={name} onChange={(event) => setName(event.target.value)} required /><select aria-label="Provider 类型" value={type} onChange={(event) => setType(event.target.value)}><option value="openai_compatible">OpenAI compatible</option><option value="ollama">Ollama</option><option value="deepl">DeepL</option><option value="libretranslate">LibreTranslate</option><option value="google_cloud_translation">Google Cloud Translation</option></select><input aria-label="Provider URL" placeholder="https://api.example.com" value={url} onChange={(event) => setUrl(event.target.value)} /><input aria-label="Provider API 密钥" type="password" placeholder="API 密钥（可选）" value={key} onChange={(event) => setKey(event.target.value)} /><button>保存 Provider</button></form><ul className="compact-list">{providers.data?.map((provider) => <li key={provider.id}><span>{provider.name} <em>{provider.health_status}</em></span><button onClick={() => void api.testProvider(provider.id).then(reload).catch((error: Error) => setMessage(error.message))}>测试</button></li>)}</ul><form onSubmit={saveModel}><select aria-label="模型 Provider" value={selectedProvider} onChange={(event) => setSelectedProvider(event.target.value)} required><option value="">选择 Provider</option>{providers.data?.map((provider) => <option key={provider.id} value={provider.id}>{provider.name}</option>)}</select><input aria-label="模型名称" placeholder="模型 ID，例如 gpt-4o-mini" value={model} onChange={(event) => setModel(event.target.value)} required /><input aria-label="输入单价" type="number" min="0" step="0.0001" placeholder="输入 $/百万 tokens" value={inputPrice} onChange={(event) => setInputPrice(event.target.value)} /><input aria-label="输出单价" type="number" min="0" step="0.0001" placeholder="输出 $/百万 tokens" value={outputPrice} onChange={(event) => setOutputPrice(event.target.value)} /><button>添加模型</button></form><ul className="compact-list">{models.data?.map((item) => <li key={item.id}>{item.display_name} <small>{item.capabilities_json.join(" · ")}</small></li>)}</ul></details>
    <details><summary>AI Functions</summary><ul className="compact-list">{functions.data?.map((item) => <li key={item.id}>{item.name} <small>v{item.prompt_version} · {item.capability}</small></li>)}</ul></details>
    <details><summary>工作流与简报</summary><ul className="compact-list">{workflows.data?.length ? workflows.data.map((item) => <li key={item.id}>{item.name} <small>{item.enabled ? "已启用" : "已停用"}</small></li>) : <li>尚未配置定时简报工作流</li>}</ul></details>
    <details><summary>任务与通知</summary><ul className="compact-list">{jobs.data?.slice(0, 5).map((item) => <li key={item.id}>{item.status} <small>{item.progress}%</small></li>)}{notifications.data?.slice(0, 5).map((item) => <li key={item.id}>{item.title}<small>{item.body}</small></li>)}</ul></details>{message && <p role="status">{message}</p>}
  </section>;
}
