import { FormEvent, useRef, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../api/client";

export function FreshRSSSettings() {
  const client = useQueryClient(); const fileInput = useRef<HTMLInputElement>(null);
  const connections = useQuery({ queryKey: ["freshrss-status"], queryFn: api.getFreshRSSStatus });
  const [base_url, setUrl] = useState(""); const [username, setUsername] = useState(""); const [api_password, setPassword] = useState(""); const [sync_interval, setInterval] = useState(900); const [message, setMessage] = useState("");
  const payload = () => ({ base_url, username, api_password, sync_interval });
  async function refreshReader() { await Promise.all([client.invalidateQueries({ queryKey: ["freshrss-status"] }), client.invalidateQueries({ queryKey: ["folders"] }), client.invalidateQueries({ queryKey: ["feeds"] }), client.invalidateQueries({ queryKey: ["entries"] })]); }
  async function sync(id: string) { try { const result = await api.syncFreshRSS(id) as { folders: number; feeds: number; entries: number }[]; const count = result[0]; setMessage(`同步完成：${count.feeds} 个订阅源，${count.entries} 篇文章`); await refreshReader(); } catch (error) { setMessage(error instanceof Error ? error.message : "同步失败"); await refreshReader(); } }
  async function submit(event: FormEvent) { event.preventDefault(); try { const saved = await api.createFreshRSS(payload()); setMessage("连接已保存，正在同步…"); await sync(saved.id); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } }
  async function importFile(file?: File) { if (!file) return; try { const result = await api.importOpml(await file.text()); setMessage(`已导入 ${result.feeds} 个 OPML 订阅源`); await refreshReader(); } catch (error) { setMessage(error instanceof Error ? error.message : "OPML 导入失败"); } finally { if (fileInput.current) fileInput.current.value = ""; } }
  async function downloadOpml() { try { const content = await api.exportOpml(); const url = URL.createObjectURL(new Blob([content], { type: "text/x-opml" })); const link = document.createElement("a"); link.href = url; link.download = "rss-ai.opml"; link.click(); URL.revokeObjectURL(url); setMessage("OPML 已下载"); } catch (error) { setMessage(error instanceof Error ? error.message : "OPML 导出失败"); } }
  const items = Array.isArray(connections.data) ? connections.data : [];
  return <section className="settings"><h2>FreshRSS 设置</h2><form onSubmit={submit}><input aria-label="FreshRSS URL" placeholder="https://freshrss.example" value={base_url} onChange={(event) => setUrl(event.target.value)} required /><input aria-label="FreshRSS 用户名" placeholder="用户名" value={username} onChange={(event) => setUsername(event.target.value)} required /><input aria-label="FreshRSS API 密码" type="password" placeholder="Google Reader API 密码" value={api_password} onChange={(event) => setPassword(event.target.value)} required /><input aria-label="同步间隔" type="number" min="60" value={sync_interval} onChange={(event) => setInterval(Number(event.target.value))} /><button type="button" onClick={() => void api.testFreshRSS(payload()).then((result) => setMessage(`连接成功：发现 ${result.subscription_count ?? 0} 个订阅源`)).catch((error: Error) => setMessage(error.message))}>测试连接</button><button type="submit">保存并同步</button></form><div className="opml-actions"><input ref={fileInput} aria-label="导入 OPML" type="file" accept=".opml,.xml,text/x-opml,application/xml" onChange={(event) => void importFile(event.target.files?.[0])} /><button type="button" onClick={() => void downloadOpml()}>导出 OPML</button></div>{message && <p role="status">{message}</p>}<ul>{items.map((connection) => <li key={connection.id}><span>{connection.base_url} · {connection.status}</span>{connection.last_error && <small className="connection-error">{connection.last_error}</small>}<button onClick={() => void sync(connection.id)}>立即同步</button></li>)}</ul></section>;
}
