import { useEffect, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { api, Entry } from "../api/client";

type Pane = "sources" | "articles" | "reader";
export function Reader() {
 const [pane,setPane]=useState<Pane>("sources"),[source,setSource]=useState<{kind:"feed"|"folder";id:string}|undefined>(),[selected,setSelected]=useState<string>(); const reader=useRef<HTMLElement>(null);
 const folders=useQuery({queryKey:["folders"],queryFn:api.getFolders}); const feeds=useQuery({queryKey:["feeds"],queryFn:api.getFeeds}); const entries=useQuery({queryKey:["entries",source],queryFn:()=>api.getEntries(source)}); const article=useQuery({queryKey:["entry",selected],queryFn:()=>api.getEntry(selected!),enabled:!!selected});
 const sourceItems=[...(folders.data??[]).map(x=>({kind:"folder" as const,id:x.id,label:x.name})),...(feeds.data??[]).map(x=>({kind:"feed" as const,id:x.id,label:x.title}))]; const entryItems=entries.data?.items??[];
 useEffect(()=>{ if(!source&&sourceItems[0])setSource(sourceItems[0]); },[source,sourceItems.length]); useEffect(()=>{setSelected(entryItems[0]?.id)},[source?.id,entryItems.map(x=>x.id).join(",")]);
 useEffect(()=>{ const onKey=(e:KeyboardEvent)=>{ if((e.target as HTMLElement)?.matches("input,textarea,select,[contenteditable=true]")||e.altKey||e.ctrlKey||e.metaKey)return; const panes:Pane[]=["sources","articles","reader"]; if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault(); setPane(p => { const i=panes.indexOf(p)+(e.key==="ArrowLeft"?-1:1); return panes[Math.max(0,Math.min(2,i))]; }); return;} if(pane==="reader"&&reader.current&&[" ","PageDown","PageUp","Home","End"].includes(e.key)){e.preventDefault();const el=reader.current; if(e.key==="Home")el.scrollTop=0;else if(e.key==="End")el.scrollTop=el.scrollHeight;else el.scrollBy({top:(e.key==="PageUp"||e.key===" "&&e.shiftKey?-1:1)*el.clientHeight,behavior:"smooth"});return;} const list=pane==="sources"?sourceItems:entryItems; if((e.key==="ArrowDown"||e.key==="ArrowUp")&&list.length){e.preventDefault();const current=pane==="sources"?source?.id:selected;const next=list[(Math.max(0,list.findIndex(x=>x.id===current)+(e.key==="ArrowDown"?1:-1)+list.length))%list.length]; if(pane==="sources")setSource(next as typeof source);else setSelected(next.id);}}; window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[pane,sourceItems,entryItems,source,selected]);
 useEffect(()=>{if(article.data&&reader.current) reader.current.scrollTop=article.data.reading_position*(reader.current.scrollHeight-reader.current.clientHeight)},[article.data?.id]);
 let scrollTimer: ReturnType<typeof setTimeout>; const onScroll=()=>{const el=reader.current;if(article.data&&el){clearTimeout(scrollTimer);const r=el.scrollHeight>el.clientHeight?el.scrollTop/(el.scrollHeight-el.clientHeight):0;scrollTimer=setTimeout(()=>void api.savePosition(article.data!.id,r),350)}};
 return <div className="reader-grid"><aside className={pane==="sources"?"active":""}><h2>Sources</h2>{sourceItems.map(x=><button key={x.id} className={source?.id===x.id?"selected":""} onClick={()=>{setSource(x);setPane("sources")}}>{x.label}</button>)}{!sourceItems.length&&<p>暂无订阅源</p>}</aside><section className={pane==="articles"?"active":""}><h2>Articles</h2>{entryItems.map(x=><button key={x.id} className={selected===x.id?"selected":""} onClick={()=>{setSelected(x.id);setPane("articles")}}>{x.title}</button>)}{!entryItems.length&&<p>暂无文章，等待 FreshRSS 同步。</p>}</section><article ref={reader} onScroll={onScroll} className={pane==="reader"?"active":""}><h2>Reader</h2>{article.data?<ReaderArticle item={article.data}/>:<p>选择一篇文章开始阅读。</p>}</article></div>;
}
function ReaderArticle({item}:{item:Entry}){return <><h1>{item.title}</h1><p>{item.author} · {new Date(item.published_at).toLocaleString()}</p><div dangerouslySetInnerHTML={{__html:item.content_html}} /></>}
