"""AI platform tables."""
import sqlalchemy as sa
from alembic import op
revision="0004_ai_platform"; down_revision="0003_freshrss_sync"; branch_labels=None; depends_on=None
def upgrade() -> None:
 u=sa.Uuid(); common=lambda n: sa.Column(n,u,primary_key=True)
 op.create_table("ai_providers",common("id"),sa.Column("name",sa.String(256),unique=True,nullable=False),sa.Column("provider_type",sa.String(64),nullable=False),sa.Column("base_url",sa.Text()),sa.Column("encrypted_api_key",sa.Text()),sa.Column("enabled",sa.Boolean(),server_default=sa.true()),sa.Column("health_status",sa.String(32),server_default="unknown"),sa.Column("timeout_seconds",sa.Integer(),server_default="60"),sa.Column("concurrency_limit",sa.Integer(),server_default="2"),sa.Column("platform_capabilities_json",sa.Text(),server_default="{}"))
 op.create_table("ai_models",common("id"),sa.Column("provider_id",u,sa.ForeignKey("ai_providers.id")),sa.Column("model_key",sa.String(256)),sa.Column("display_name",sa.String(256)),sa.Column("capabilities_json",sa.Text(),server_default="[]"),sa.Column("context_limit",sa.Integer(),server_default="8192"),sa.Column("max_output",sa.Integer(),server_default="2048"),sa.Column("is_local",sa.Boolean(),server_default=sa.false()),sa.Column("cost_config_json",sa.Text(),server_default="{}"),sa.Column("priority",sa.Integer(),server_default="100"),sa.Column("enabled",sa.Boolean(),server_default=sa.true()))
 op.create_table("routing_policies",common("id"),sa.Column("name",sa.String(256),unique=True),sa.Column("capability",sa.String(128)),sa.Column("strategy",sa.String(64),server_default="priority"),sa.Column("fallback_chain_json",sa.Text(),server_default="[]"))
 op.create_table("ai_functions",common("id"),sa.Column("name",sa.String(256)),sa.Column("function_key",sa.String(256),unique=True),sa.Column("description",sa.Text(),server_default=""),sa.Column("input_scope",sa.String(32),server_default="single"),sa.Column("capability",sa.String(128)),sa.Column("prompt_template",sa.Text()),sa.Column("prompt_version",sa.Integer(),server_default="1"),sa.Column("output_schema_json",sa.Text()),sa.Column("default_routing_policy_id",u,sa.ForeignKey("routing_policies.id")),sa.Column("enabled",sa.Boolean(),server_default=sa.true()))
 op.create_table("workflows",common("id"),sa.Column("name",sa.String(256),unique=True),sa.Column("scope_config_json",sa.Text(),server_default="{}"),sa.Column("selection_config_json",sa.Text(),server_default="{}"),sa.Column("pipeline_config_json",sa.Text(),server_default="{}"),sa.Column("output_config_json",sa.Text(),server_default="{}"),sa.Column("schedule_config_json",sa.Text(),server_default="{}"),sa.Column("enabled",sa.Boolean(),server_default=sa.true()),sa.Column("last_success_at",sa.DateTime(timezone=True)))
 op.create_table("ai_jobs",common("id"),sa.Column("workflow_id",u,sa.ForeignKey("workflows.id")),sa.Column("function_id",u,sa.ForeignKey("ai_functions.id")),sa.Column("status",sa.String(32),server_default="queued"),sa.Column("progress",sa.Integer(),server_default="0"),sa.Column("input_article_count",sa.Integer(),server_default="1"),sa.Column("entry_set_hash",sa.String(64)),sa.Column("provider_id",u,sa.ForeignKey("ai_providers.id")),sa.Column("model_id",u,sa.ForeignKey("ai_models.id")),sa.Column("usage_json",sa.Text(),server_default="{}"),sa.Column("estimated_cost",sa.Float(),server_default="0"),sa.Column("error_json",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("finished_at",sa.DateTime(timezone=True)))
 op.create_table("ai_artifacts",common("id"),sa.Column("job_id",u,sa.ForeignKey("ai_jobs.id")),sa.Column("entry_id",u,sa.ForeignKey("entries.id")),sa.Column("artifact_type",sa.String(128)),sa.Column("language",sa.String(32)),sa.Column("content_markdown",sa.Text()),sa.Column("content_json",sa.Text()),sa.Column("content_hash",sa.String(64)),sa.Column("prompt_version",sa.Integer()),sa.Column("model_id",u,sa.ForeignKey("ai_models.id")),sa.Column("configuration_hash",sa.String(64)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("is_current",sa.Boolean(),server_default=sa.true()))
 op.create_table("app_settings",sa.Column("key",sa.String(256),primary_key=True),sa.Column("value_json",sa.Text()),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table("notifications",common("id"),sa.Column("title",sa.String(512)),sa.Column("body",sa.Text()),sa.Column("is_read",sa.Boolean(),server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
def downgrade() -> None:
 [op.drop_table(x) for x in ["notifications","app_settings","ai_artifacts","ai_jobs","workflows","ai_functions","routing_policies","ai_models","ai_providers"]]
